/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesIndexImport } from './routes/recipes/index'
import { Route as CatsIndexImport } from './routes/cats/index'
import { Route as ExamplesTanstackQueryImport } from './routes/examples/tanstack-query'
import { Route as ExamplesTableImport } from './routes/examples/table'
import { Route as ExamplesShadcnImport } from './routes/examples/shadcn'
import { Route as ExamplesJotaiImport } from './routes/examples/jotai'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRoute,
} as any)

const CatsIndexRoute = CatsIndexImport.update({
  id: '/cats/',
  path: '/cats/',
  getParentRoute: () => rootRoute,
} as any)

const ExamplesTanstackQueryRoute = ExamplesTanstackQueryImport.update({
  id: '/examples/tanstack-query',
  path: '/examples/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const ExamplesTableRoute = ExamplesTableImport.update({
  id: '/examples/table',
  path: '/examples/table',
  getParentRoute: () => rootRoute,
} as any)

const ExamplesShadcnRoute = ExamplesShadcnImport.update({
  id: '/examples/shadcn',
  path: '/examples/shadcn',
  getParentRoute: () => rootRoute,
} as any)

const ExamplesJotaiRoute = ExamplesJotaiImport.update({
  id: '/examples/jotai',
  path: '/examples/jotai',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/examples/jotai': {
      id: '/examples/jotai'
      path: '/examples/jotai'
      fullPath: '/examples/jotai'
      preLoaderRoute: typeof ExamplesJotaiImport
      parentRoute: typeof rootRoute
    }
    '/examples/shadcn': {
      id: '/examples/shadcn'
      path: '/examples/shadcn'
      fullPath: '/examples/shadcn'
      preLoaderRoute: typeof ExamplesShadcnImport
      parentRoute: typeof rootRoute
    }
    '/examples/table': {
      id: '/examples/table'
      path: '/examples/table'
      fullPath: '/examples/table'
      preLoaderRoute: typeof ExamplesTableImport
      parentRoute: typeof rootRoute
    }
    '/examples/tanstack-query': {
      id: '/examples/tanstack-query'
      path: '/examples/tanstack-query'
      fullPath: '/examples/tanstack-query'
      preLoaderRoute: typeof ExamplesTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/cats/': {
      id: '/cats/'
      path: '/cats'
      fullPath: '/cats'
      preLoaderRoute: typeof CatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/jotai': typeof ExamplesJotaiRoute
  '/examples/shadcn': typeof ExamplesShadcnRoute
  '/examples/table': typeof ExamplesTableRoute
  '/examples/tanstack-query': typeof ExamplesTanstackQueryRoute
  '/cats': typeof CatsIndexRoute
  '/recipes': typeof RecipesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/jotai': typeof ExamplesJotaiRoute
  '/examples/shadcn': typeof ExamplesShadcnRoute
  '/examples/table': typeof ExamplesTableRoute
  '/examples/tanstack-query': typeof ExamplesTanstackQueryRoute
  '/cats': typeof CatsIndexRoute
  '/recipes': typeof RecipesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/examples/jotai': typeof ExamplesJotaiRoute
  '/examples/shadcn': typeof ExamplesShadcnRoute
  '/examples/table': typeof ExamplesTableRoute
  '/examples/tanstack-query': typeof ExamplesTanstackQueryRoute
  '/cats/': typeof CatsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples/jotai'
    | '/examples/shadcn'
    | '/examples/table'
    | '/examples/tanstack-query'
    | '/cats'
    | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples/jotai'
    | '/examples/shadcn'
    | '/examples/table'
    | '/examples/tanstack-query'
    | '/cats'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/examples/jotai'
    | '/examples/shadcn'
    | '/examples/table'
    | '/examples/tanstack-query'
    | '/cats/'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesJotaiRoute: typeof ExamplesJotaiRoute
  ExamplesShadcnRoute: typeof ExamplesShadcnRoute
  ExamplesTableRoute: typeof ExamplesTableRoute
  ExamplesTanstackQueryRoute: typeof ExamplesTanstackQueryRoute
  CatsIndexRoute: typeof CatsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesJotaiRoute: ExamplesJotaiRoute,
  ExamplesShadcnRoute: ExamplesShadcnRoute,
  ExamplesTableRoute: ExamplesTableRoute,
  ExamplesTanstackQueryRoute: ExamplesTanstackQueryRoute,
  CatsIndexRoute: CatsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/examples/jotai",
        "/examples/shadcn",
        "/examples/table",
        "/examples/tanstack-query",
        "/cats/",
        "/recipes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/examples/jotai": {
      "filePath": "examples/jotai.tsx"
    },
    "/examples/shadcn": {
      "filePath": "examples/shadcn.tsx"
    },
    "/examples/table": {
      "filePath": "examples/table.tsx"
    },
    "/examples/tanstack-query": {
      "filePath": "examples/tanstack-query.tsx"
    },
    "/cats/": {
      "filePath": "cats/index.tsx"
    },
    "/recipes/": {
      "filePath": "recipes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
