export const themes = [
  'light',
  'dark',
  // 'mos',
  // 'nord',
  // 'dark2',
  // 'aqua',
  // 'black',
  // 'bumblebee',
  // 'cmyk',
  // 'corporate',
  // 'cupcake',
  // 'cyberpunk',
  // 'dracula',
  // 'emerald',
  // 'fantasy',
  // 'forest',
  // 'garden',
  // 'halloween',
  // 'luxury',
  // 'pastel',
  // 'retro',
  // 'synthwave',
  // 'valentine',
  // 'wireframe',
  // 'autumn',
  // 'business',
  // 'acid',
  // 'lemonade',
  // 'night',
  // 'coffee',
  // 'winter',
  // 'dim',
  // 'sunset',
];
